$(document).ready(function(){
    $("#mycarousel").carousel({interval:2000 });
    $("#carouselButton").click(function(){
        if($("#carouselButton").children("span").hasClass("fa-pause")){
            $("#mycarousel").carousel('pause');
            $("#carouselButton").children("span").removeClass("fa-pause");
            $("#carouselButton").children("span").addClass("fa-play");
        }
        else{
            $("#mycarousel").carousel('cycle');
            $("#carouselButton").children("span").removeClass("fa-play");
            $("#carouselButton").children("span").addClass("fa-pause");
        }
        
    });
    $("#login").click(function(){
        $("#loginModal").modal("toggle");
    });
    $("#closebutton").click(function(){
        $("#loginModal").modal("toggle");
    });
    $("#cancelbutton").click(function(){
        $("#loginModal").modal("toggle");
    });
    $("#cancel").click(function(){
        $("#reserveModal").modal("toggle");
    });
    $("#reservetable").click(function(){
        $("#reserveModal").modal("toggle");
    });
    /*$("#carousel-pause").click(function(){
        $("#mycarousel").carousel('pause');
    });
    $("#carousel-play").click(function(){
        $("#mycarousel").carousel('cycle');
    });*/
});
